[[package]]
name = "autd3-link-soem"
license_file_url = "https://raw.githubusercontent.com/shinolab/autd3-rs/master/autd3-link-soem/LICENSE"

[[package]]
name = "autd3-link-twincat"
license_file_url = "https://raw.githubusercontent.com/shinolab/autd3-rs/master/autd3-link-twincat/LICENSE"
